### PR TITLE
ready for review

### PR DESCRIPTION
**Pull request by akinloludavid**
- I've completed the assessment. Kindly review @uchibeke

### CODE REVIEW

**Comment by uchibeke** [comment]
Did you test this properly because I am unable to sign up as a new user nighter am I able to log in

This is the bare minimum you should have tested and retested and ensured it works

**Comment by akinloludavid** [comment]
> Did you test this properly because I am unable to sign up as a new user nighter am I able to log in
> 
> This is the bare minimum you should have tested and retested and ensured it works

I tested every endpoint and they all work. The live link here: https://chimoney-ak-test.netlify.app/
The backend hosting goes to sleep mode when there is inactivity because it is a free tier hosting and takes a while to come back up. Apologies for that

I recorded a loom video here: https://www.loom.com/share/8e0a781528824241bea9acf4d600fe52?sid=7fea3812-3737-4d86-b4f4-192ba64beb44

**Comment by akinloludavid** [comment]
> > Did you test this properly because I am unable to sign up as a new user nighter am I able to log in
> > This is the bare minimum you should have tested and retested and ensured it works
> 
> I tested every endpoint and it works. The live link here: https://chimoney-ak-test.netlify.app/ The backend hosting goes to sleep mode when there is inactivity because it is a free tier hosting and takes a while to come back up
> 
> I recorded a loom video here: https://www.loom.com/share/8e0a781528824241bea9acf4d600fe52?sid=7fea3812-3737-4d86-b4f4-192ba64beb44

@uchibeke

**Comment by uchibeke** [comment]
> > > Did you test this properly because I am unable to sign up as a new user nighter am I able to log in
> > > This is the bare minimum you should have tested and retested and ensured it works
> > 
> > 
> > I tested every endpoint and it works. The live link here: https://chimoney-ak-test.netlify.app/ The backend hosting goes to sleep mode when there is inactivity because it is a free tier hosting and takes a while to come back up
> > I recorded a loom video here: https://www.loom.com/share/8e0a781528824241bea9acf4d600fe52?sid=7fea3812-3737-4d86-b4f4-192ba64beb44
> 
> @uchibeke

Ok. Seen.


Is there a reason why any user can see other user transactions? What’s the justification for this?

**Comment by akinloludavid** [comment]
> > > > Did you test this properly because I am unable to sign up as a new user nighter am I able to log in
> > > > This is the bare minimum you should have tested and retested and ensured it works
> > > 
> > > 
> > > I tested every endpoint and it works. The live link here: https://chimoney-ak-test.netlify.app/ The backend hosting goes to sleep mode when there is inactivity because it is a free tier hosting and takes a while to come back up
> > > I recorded a loom video here: https://www.loom.com/share/8e0a781528824241bea9acf4d600fe52?sid=7fea3812-3737-4d86-b4f4-192ba64beb44
> > 
> > 
> > @uchibeke
> 
> Ok. Seen.
> 
> Is there a reason why any user can see other user transactions? What’s the justification for this?

@uchibeke all the users in this app shared the same api key and there was no endpoint for transactions for unique user.  I thought the api was designed that way because it is a sandbox.

**Comment by uchibeke** [comment]
> > > > > Did you test this properly because I am unable to sign up as a new user nighter am I able to log in
> > > > > This is the bare minimum you should have tested and retested and ensured it works
> > > > 
> > > > 
> > > > I tested every endpoint and it works. The live link here: https://chimoney-ak-test.netlify.app/ The backend hosting goes to sleep mode when there is inactivity because it is a free tier hosting and takes a while to come back up
> > > > I recorded a loom video here: https://www.loom.com/share/8e0a781528824241bea9acf4d600fe52?sid=7fea3812-3737-4d86-b4f4-192ba64beb44
> > > 
> > > 
> > > @uchibeke
> > 
> > 
> > Ok. Seen.
> > Is there a reason why any user can see other user transactions? What’s the justification for this?
> 
> @uchibeke all the users in this app shared the same api key and there was no endpoint for transactions for unique user. I thought the api was designed that way because it is a sandbox.

This is not how it is designed. Did you check out the sub account?

**Pull request merged**
